# Generated by Django 5.1.7 on 2025-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reefapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coralimage',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Bleached', 'Bleached'), ('Partially Bleached', 'Partially Bleached'), ('Processing', 'Processing')], default='Processing', max_length=20),
        ),
    ]
